title: Chris Hancock | Developer
email: hi@chancock.com
description: >
  Chris builds the internet in 2017.
baseurl: ""
url: "http://chancock.com"
facebook_username: chancock09
github_username:  chancock09
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:title/
